connorworley/karafriends

src/common/schema.graphql
src/main/damApi.ts
src/main/graphql.ts
src/remocon/App.tsx
src/remocon/Artist.tsx
src/remocon/ArtistSearch.tsx
src/remocon/Search.tsx
src/remocon/Song.tsx
src/remocon/SongSearch.tsx
src/remocon/__generated__/ArtistQuery.graphql.ts
src/remocon/__generated__/ArtistSearchQuery.graphql.ts
src/remocon/components/DebouncedInput.tsx
src/remocon/components/Loader.tsx

dam pages are not real pages. they just give you everything if you request page = totalPage.
there's also no real way to get only artist info from artist id. it will always include the songs.
Search
Search by song title
Search by artist
List artist's songs
Click through to song

Add artist search functionality

---

src/main/graphql.ts

Support whitespace in romaji searches

---

src/common/schema.graphql
src/main/graphql.ts
src/remocon/Controls.tsx
src/remocon/Song.tsx
src/remocon/__generated__/ControlsQueueQuery.graphql.ts
src/remocon/__generated__/ControlsRemoveSongMutation.graphql.ts
src/remocon/__generated__/SongMutation.graphql.ts
src/renderer/Player.tsx
src/renderer/__generated__/PlayerPopSongMutation.graphql.ts

fixes #34 
it no longer errors.
and yes, it still doesn't update the queue shown to the user when the item is deleted.
need to figure out subscriptions or something

Rename id on QueueItem to songId

---

src/main/damApi.ts
src/main/graphql.ts

https://pshuu.moe/4Ku/S2zLZE.png

use dkwebsys for music detail

---

src/common/schema.graphql
src/main/graphql.ts
src/remocon/Song.tsx
src/remocon/__generated__/SongQuery.graphql.ts

Display tieUp data on song detail page

---

src/common/schema.graphql
src/main/damApi.ts
src/main/graphql.ts
src/remocon/App.tsx
src/remocon/History.tsx
src/remocon/Song.tsx
src/remocon/__generated__/HistoryPaginationQuery.graphql.ts
src/remocon/__generated__/HistoryViewQuery.graphql.ts
src/remocon/__generated__/History_history.graphql.ts
src/remocon/__generated__/SongQuery.graphql.ts
src/remocon/components/QueueButton.tsx
src/remocon/components/__generated__/QueueButtonMutation.graphql.ts
src/renderer/Player.tsx
src/renderer/__generated__/PlayerPopSongMutation.graphql.ts

Add history page and delay fetching streaming urls until play time

---

src/renderer/PianoRoll.tsx

fix STROKE_WIDTH constant

---

scripts/getExternalResources.mjs

This should fix the build because the problem was the windows builder not being able to download the linux static build, which it actually doesn't need

Only download platform relevant external resources

---

src/common/videoDownloader.ts
src/main/graphql.ts
src/main/index.ts
src/renderer/Player.tsx

Not sure why hooks reformatted stuff in main/index.ts

Save DAM songs to disk and then use them

---

package.json
src/common/config.ts
src/common/schema.graphql
src/common/videoDownloader.ts
src/main/graphql.ts
src/remocon/AddNico.tsx
src/remocon/Controls.tsx
src/remocon/CurrentSong.tsx
src/remocon/NicoInfo.css
src/remocon/NicoInfo.tsx
src/remocon/Search.tsx
src/remocon/YoutubeInfo.tsx
src/remocon/components/NicoQueueButton.tsx
src/renderer/Player.tsx
webpack.config.js
yarn.lock

Videos from Niconico can be downloaded and added to the queue now
Queue limit can also be adjusted from local configs. Requires a restart to reload it though.
Also fixed the minor ffmpeg filepath bug

Add Niconico support. Let queue limit be adjustable. Add local configs

---

package.json
src/renderer/Player.tsx
yarn.lock

Kind of fluff feature but this puts song info in MediaSession (which maps into the platform media session metadata)

Add current song info to mediasession

---

src/remocon/components/ControlBar/ControlBar.module.scss
src/remocon/components/ControlBar/ControlBar.tsx
src/remocon/components/EmoteButtons/EmoteButtons.module.scss
src/remocon/components/EmoteButtons/EmoteButtons.tsx

Made various improvements to emotes in the remocon
- Fixed the emote buttons getting selected on long press
- Made it easier to spam emotes by holding down emote buttons
- Made emote buttons larger and toggle against playback controls
- Made emotes customizable
- Persist the expanded state, emote/playback toggle state, custom emotes in localStorage

Remocon emote improvements

---

.github/workflows/build.yaml
package.json
src/common/config.ts
src/common/graphqlEnvironment.ts
src/main/graphql.ts
src/main/index.ts
src/preload/index.ts
src/renderer/HostnameSetting.tsx
src/renderer/Player.tsx
src/renderer/QRCode.tsx
src/renderer/global.ts

Sometimes 8080 is already bound

Make listening port configurable

---

src/common/joysoundParser.ts
src/renderer/JoysoundRenderer.tsx

Fix Joysound lyrics kerning + center romaji

---

src/common/videoDownloader.ts
src/renderer/JoysoundRenderer.tsx
src/renderer/Player.tsx
src/renderer/joysoundParser.ts

code is gross, will clean up someday

Add joysound titlecard

---

src/common/schema.graphql
src/common/videoDownloader.ts
src/main/graphql.ts
src/remocon/components/JoysoundQueueButtons/JoysoundQueueButton.tsx
src/remocon/pages/JoysoundSongPage.tsx

Add download queue and downloading button

---

src/common/schema.graphql
src/renderer/Effects.tsx

Small fix for emotes since the last schema change broke the subscription.

Fix emotes

---

src/main/index.ts
src/remocon/index.tsx
src/renderer/index.tsx

Probably should adjust the list since other DSNs like *.ingest.sentry.io are possible

Add sentry/browser

---

src/remocon/components/JoysoundQueueButtons/JoysoundQueueButton.tsx
src/remocon/components/JoysoundYouTubeInfo/JoysoundYouTubeInfo.module.scss
src/remocon/components/JoysoundYouTubeInfo/JoysoundYouTubeInfo.tsx
src/remocon/pages/JoysoundSongPage.tsx

Joysound YouTube background video attachment UX improvement

---

src/common/hooks/usePlaybackState.ts
src/common/hooks/useQueue.ts
src/remocon/components/YouTubeInfo/YouTubeLyricsForm.tsx
src/remocon/hooks/useNowPlaying.ts

this was actually giving me so much cancer

re-render on visibilitychange

---

src/common/joysoundParser.ts
src/main/joysoundApi.ts
src/renderer/JoysoundRenderer.tsx
src/renderer/Player.tsx

- fixed ◯ turning into ◆ in song lyrics
- fixed title card being rendered incorrectly
- fixed joysound api text staying escaped
- fixed multiple queue polling timeouts on initial render

fixed a bunch of stuff

---

src/common/config.ts
src/common/schema.graphql
src/common/videoDownloader.ts
src/main/graphql.ts
src/remocon/components/DamQueueButtons/DamQueueButton.tsx
src/remocon/components/JoysoundQueueButtons/JoysoundQueueButton.tsx
src/remocon/components/NiconicoInfo/NiconicoQueueButton.tsx
src/remocon/components/YouTubeInfo/YouTubeQueueButton.tsx

UI for warikomi is holding Shift for focused insertion because I'm terrible at React

Defining admins statically in config / Implement queue head overrides
